// <auto-generated />
namespace TatilSeyahatSitesi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adding_feature_otelAciklama : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_feature_otelAciklama));
        
        string IMigrationMetadata.Id
        {
            get { return "202310071239530_adding_feature_otelAciklama"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
