// <auto-generated />
namespace TatilSeyahatSitesi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adding_virtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_virtual));
        
        string IMigrationMetadata.Id
        {
            get { return "202310040636191_adding_virtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
